#!/bin/sh

export MONO_PATH=/usr/lib/monodevelop/bin

cobra -compile -include-tests:no -color:yes -debug:full -pkg:monodevelop -pkg:gtk-sharp-2.0 -ref:System.Core -ref:../Gui/bin/Debug/MonoDevelop.CobraBinding.Gui.dll -sharp-args:"-res:\"CobraBinding.addin.xml,CobraBinding.addin.xml\" -res:\"CobraSyntaxMode.xml,CobraSyntaxMode.xml\" -res:\"templates/ConsoleProject.xpt.xml,ConsoleProject.xpt.xml\" -res:\"templates/EmptyCobraFile.xft.xml,EmptyCobraFile.xft.xml\" -res:\"templates/EmptyProject.xpt.xml,EmptyProject.xpt.xml\" -res:\"templates/GtkSharp2Project.xpt.xml,GtkSharp2Project.xpt.xml\" -res:\"templates/LibraryProject.xpt.xml,LibraryProject.xpt.xml\"" -target:lib -out:"bin/Debug/MonoDevelop.CobraBinding.dll" AssemblyInfo.cs *.cobra Project/*.cobra TypeSystem/*.cobra Completion/*.cobra
